# Build starts faster without `sudo`
sudo: false

language: c
compiler: gcc
os: osx

cache:
  directories:
  - $HOME/.stack
  - $HOME/.local/bin
  - $TRAVIS_BUILD_DIR/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/HaRe/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/ghc-mod/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/ghc-mod/core/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/haskell-lsp/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/haskell-lsp/haskell-lsp-types/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/cabal-helper/.stack-work
  - $TRAVIS_BUILD_DIR/hie-plugin-api/.stack-work
  timeout: 800

env:
  - ARGS="--stack-yaml=stack-8.4.3.yaml"
  - ARGS="--stack-yaml=stack-8.4.2.yaml"
  - ARGS="--stack-yaml=stack-8.2.2.yaml"
  - ARGS="--stack-yaml=stack-8.2.1.yaml"

before_install:
  - mkdir -p $HOME/.stack
  - mkdir -p ~/.local/bin
  - |
    if [[ ! -f "${HOME}/.local/bin/stack" ]]
    then
      travis_retry curl -sSL https://www.stackage.org/stack/${TRAVIS_OS_NAME}-x86_64 \
        | tar xz --strip-components=1 -C ~/.local/bin --include   '*/stack'
    fi
  - travis_retry stack --no-terminal --install-ghc $ARGS setup

script:
  - stack build --test $ARGS
  - stack exec hoogle generate $ARGS
  - stack test $ARGS
