resolver: nightly-2018-12-01 # GHC 8.6.2
packages:
- .
- hie-plugin-api

extra-deps:
- ./submodules/HaRe
- ./submodules/brittany
- ./submodules/cabal-helper
- ./submodules/ghc-mod
- ./submodules/ghc-mod/core

- apply-refact-0.6.0.0
- butcher-1.3.2.1
- cabal-plan-0.4.0.0
- constrained-dynamic-0.1.0.0
- ekg-json-0.1.0.6
- ekg-wai-0.1.0.3
- haddock-api-2.21.0
- hsimport-0.8.6
- monad-memo-0.4.1
- multistate-0.8.0.1
- resolv-0.1.1.2
- lsp-test-0.5.0.2
- pretty-show-1.8.2
- syz-0.2.0.0
- temporary-1.2.1.1
- yaml-0.8.32
- github: LeastAuthority/hspec-jenkins
  commit: master




flags:
  haskell-ide-engine:
    pedantic: true
  hie-plugin-api:
    pedantic: true

nix:
  packages: [ icu libcxx zlib ]

concurrent-tests: false
