resolver: nightly-2018-12-31 # GHC 8.6.3
packages:
- .
- hie-plugin-api

extra-deps:
- ./submodules/HaRe
- ./submodules/brittany
- ./submodules/cabal-helper
- ./submodules/ghc-mod
- ./submodules/ghc-mod/core
# - ./../cabal-helper
# - ./../ghc-mod
# - ./../ghc-mod/core

- butcher-1.3.2.1
- cabal-plan-0.5.0.0
- constrained-dynamic-0.1.0.0
- ekg-json-0.1.0.6
- ekg-wai-0.1.0.3
- haddock-api-2.21.0
- hsimport-0.8.6
- monad-memo-0.4.1
- multistate-0.8.0.1
- optparse-simple-0.1.0
- pretty-show-1.8.2
- syz-0.2.0.0
- temporary-1.2.1.1
- yaml-0.8.32

flags:
  haskell-ide-engine:
    pedantic: true
  hie-plugin-api:
    pedantic: true

# allow-newer: true

nix:
  packages: [ icu libcxx zlib ]

concurrent-tests: false
